### PR TITLE
Add PHP Architecture Tester

### PR DESCRIPTION
**Pull request by carlosas**
PHP Architecture Tester is a static analysis tool to verify architectural requirements.
It provides a natural language abstraction to define your own architectural rules and test them against your software.

There are four groups of supported assertions: Dependency, Inheritance, Composition and Mixin.

### CODE REVIEW

**Comment by carlosas-cmp** [comment]
That was quick 😂
Thank you!

**Comment by carlosas** [comment]
That was quick 😂
Thank you!

**Comment by andreasschroth** [comment]
Your PR isn't merged though...

**Comment by carlosas** [comment]
Obvious thing. I replied to the review in 2 minutes :slightly_smiling_face:

**Comment by carlosas** [comment]
@exakat is this repo still active? 🤔

**Comment by exakat** [comment]
Thanks Carlos. Yes, still active.

**Pull request merged**
